version: '3'
services:
  banco:
    container_name: banco
    image: bdii/banco
    build: ./database
    ports: 
     - "5433:5432" 
  app:
    container_name: app
    image: bdii/app
    build: 
      context: ../
      dockerfile: ./env/app/Dockerfile
    ports: 
     - "4444:4444"
    depends_on:
      - banco
    deploy:
      restart_policy:
        condition: on-failure